import streamlit as st
import joblib
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# -------------------------------------
# Download NLTK Resources
# -------------------------------------
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

# -------------------------------------
# Create Lemmatizer
# -------------------------------------
lemmatizer = WordNetLemmatizer()

# Load English stopwords
stop_words = set(stopwords.words("english"))

# -------------------------------------
# Text Cleaning Function
# -------------------------------------
def clean_text(text):

    # Convert text into lowercase
    text = text.lower()

    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Split sentence into words
    words = word_tokenize(text)

    # Remove stopwords and lemmatize words
    cleaned_words = []

    for word in words:

        if word not in stop_words:
            word = lemmatizer.lemmatize(word)
            cleaned_words.append(word)

    # Join words back into one sentence
    cleaned_text = " ".join(cleaned_words)

    return cleaned_text
# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(
    page_title="Fake News Detection",
    page_icon="📰",
    layout="centered"
)

# -------------------------------
# Load Model and Vectorizer
# -------------------------------
model = joblib.load("models/best_fake_news_model.pkl")
vectorizer = joblib.load("models/bow_vectorizer.pkl")

# ==========================================
# Sidebar
# ==========================================

st.sidebar.title("📰 About Project")

st.sidebar.markdown("---")

st.sidebar.subheader("📂 Dataset")
st.sidebar.write("WELFake Dataset")

st.sidebar.subheader("🤖 Model")
st.sidebar.write("Neural Network (MLP Classifier)")

st.sidebar.subheader("📝 Feature Extraction")
st.sidebar.write("Bag of Words")

st.sidebar.subheader("🎯 Accuracy")
st.sidebar.success("96.46%")

st.sidebar.markdown("---")

st.sidebar.subheader("👨‍💻 Developer")
st.sidebar.write("Ashutosh Sharma")

st.sidebar.write("CSE Student at Government Hydro Engineering College Bandla Bilaspur (H.P)")

st.sidebar.markdown("---")

st.sidebar.info(
    "This application predicts whether a news article is likely to be Real or Fake using a Machine Learning model."
)

# -------------------------------
# Title
# -------------------------------
st.title("📰 AI-Powered Fake News Detection System")

st.caption(
    "Machine Learning Based Fake News Classification using Bag of Words and Neural Network"
)
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Model", "MLP")

with col2:
    st.metric("Accuracy", "96.46%")

with col3:
    st.metric("Dataset", "WELFake")

st.markdown("""
Detect whether a news article is **Real** or **Fake** using an AI-powered Machine Learning model.

### Instructions
1. Paste the complete news article into the text box.
2. Click **Predict News**.
3. View the prediction and confidence score.
""")

st.success("✅ Model and Vectorizer Loaded Successfully!")

# -------------------------------
# Text Input
# -------------------------------
news_text = st.text_area(
    "📝 Paste the News Article Here",
    height=250,
    placeholder="Paste the complete news article here..."
)
# -------------------------------
# Predict Button
# -------------------------------
if st.button("🔍 Predict News"):

    # Check if the user entered any text
    if news_text.strip() == "":
        st.warning("⚠ Please enter a news article.")

    else:

        # Clean the input text
        cleaned_news = clean_text(news_text)

        # Convert text into Bag of Words features
        news_vector = vectorizer.transform([cleaned_news])

        # Make prediction
        prediction = model.predict(news_vector)
        probability = model.predict_proba(news_vector)

        # Convert probabilities into percentages
        real_confidence = probability[0][0] * 100
        fake_confidence = probability[0][1] * 100

       
        # -------------------------------
        # Display Prediction
        # -------------------------------
        if prediction[0] == 0:
            st.success("✅ Prediction: REAL NEWS")
        else:
            st.error("❌ Prediction: FAKE NEWS")

        st.subheader("Prediction Confidence")

        st.write(f"🟢 Real News : {real_confidence:.2f}%")
        st.progress(real_confidence / 100)

        st.write(f"🔴 Fake News : {fake_confidence:.2f}%")
        st.progress(fake_confidence / 100)
        
        st.markdown("---")

st.caption(
    "⚠️ Disclaimer: This prediction is generated by a machine learning model and should not be treated as definitive  verification. Always verify important news using trusted sources."
)
st.markdown("---")

st.markdown(
    """
    <div style="text-align:center;">
        <h4>📰 Fake News Detection System</h4>
        <p>Developed by <b>Ashutosh Sharma</b></p>
        
    </div>
    """,
    unsafe_allow_html=True
)